### PR TITLE
fix: protocal address condition fix

### PR DESCRIPTION
**Pull request by pravin120993**
fix for Unsupported protocol

### CODE REVIEW

**Comment by pravin120993** [comment]
this pr is for this https://github.com/ProjectOpenSea/opensea-js/issues/852

**Comment by pravin120993** [comment]
@pi9min check this PR. i have closed my PR

**Comment by pravin120993** [comment]
Screenshot 2023-03-06 at 10 58 16 PM

**Comment by JoshuaSchmidt-OpenSea** [comment]
This has been published to version `4.0.18`

**Pull request merged**
